# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  postmanDockerRun:
    name: Postman test with report # Docker Power
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: Postman
        run: |
          docker pull reportportal/newman      
          docker run -t reportportal/newman run https://raw.githubusercontent.com/procesor2017/gitHubWorkShop/master/test/Postman/TestApi.json \
          -r @reportportal/reportportal \
          --reporter-@reportportal/reportportal-debug=true \
          --reporter-@reportportal/reportportal-endpoint=http://portal.tesena.com/api/v1 \
          --reporter-@reportportal/reportportal-token=${{ secrets.UUID }} \
          --reporter-@reportportal/reportportal-launch=${{ secrets.LAUNCH }} \
          --reporter-@reportportal/reportportal-project=${{ secrets.PROJECT }} \
          -x
