name: blank

# Běh každou hodinu
on:
  push:
    branches: 
      - master
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  k6:
    runs-on: ubuntu-latest
    name: Start install
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
          echo "deb https://dl.bintray.com/loadimpact/deb stable main" | sudo tee -a /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install k6
      - name: try to start just k6
        run: | 
          npm install k6-to-junit
          cd ${{ github.workspace }}/test/k6
          k6 run loadtest.js | k6-to-junit junit.xml
          ls junit.xml
          zip junit.zip junit.xml
          curl -X POST --header 'Content-Type: multipart/form-data' --header 'Accept: application/json' --header 'Authorization: bearer ${{ secrets.UUID }}' -F file=@junit.zip 'http://portal.tesena.com/api/v1/JAN_EGERMAIER_PERSONAL/launch/import'
          {"msg":"Launch with id = 001 is successfully imported."}

      - name: Try to start mocha and k6
        run: | 
          cd ${{ github.workspace }}/test/k6
          npm test
  
