# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  postmanDockerRun:
    name: Playwright 
    runs-on: ubuntu-latest
    env:
      endpoint: ${{ secrets.ENDPOINT }}
      token: ${{ secrets.UUID }}
      launch: ${{ secrets.LAUNCH }}
      project: ${{ secrets.PROJECT }}
      description: Test from github actions
    steps:
      - uses: actions/checkout@v2.3.2
      - name: Playwright
        run: |
          echo ahoj $endpoint
          cd ${{ github.workspace }}/test/playwright
          npm install
          npm update
          npm test


