name: GitHub-CI
on: 
  [push]

# Jednoduchý příklad pro vypsání Ahoj :-)
jobs:
  build:
    name: Vítej
    runs-on: ubuntu-latest
    steps:
      - name: Ahoj
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Batman'
        id: ahoj
  # Startujeme RF test na API = Ukázka instalace pythonu a dalších závislostí.
  robotApiTest:
    name: robotApiTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-requests 
      - name: Start test
        run: | 
          python -m robot -i api RobotFrameWork/tc.robot
  # Docker and robot framework --RobotFrameWork
  robotWebTest:
    name: robotWebTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker for RF
        uses: docker://ppodgorsek/robot-framework
      - name: start
        run: |
          python -m pip install --upgrade pip
