name: GitHub-CI
on: 
  [push]

# Jednoduchý příklad pro vypsání Ahoj :-)
jobs:
  build:
    name: Vítej
    runs-on: ubuntu-latest
    steps:
      - name: Ahoj
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Batman'
        id: ahoj

  # Startujeme RF test na API = Ukázka instalace pythonu a dalších závislostí.
  robotApiTest:
    name: robotApiTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-requests 
      - name: Start test
        run: | 
          python -m robot -i api test/RobotFrameWork/tc.robot

  # Docker and robot framework =Využíté Dockeru
  robotWebTest:
    name: robotWebTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker for RF
        run: |
          docker run --shm-size=1g \
          -v ${{ github.workspace }}/test/RobotFrameWork:/opt/robotframework/reports:Z \
          -v ${{ github.workspace }}/test/RobotFrameWork:/opt/robotframework/tests:Z \
          -e BROWSER=chrome \
          --user=1001:1001 \
          ppodgorsek/robot-framework:latest
          
  #K6 Load Test = Využítí již před přiravených actions
  loadTest:
    name: k6 Load Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run k6 local test
        uses: k6io/action@v0.1
        with:
          filename: ${{ github.workspace }}/test/k6/loadtest.js
          flags: --vus 50 --duration 10s
  
  # Code quality = Ukázka využítí secrets
  codeQuality:
    name: Code Quality test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  #WebPage speed = Spouští se pouze pokud passne loadTest
  webPageSpeed:
    needs: [loadTest]
    name: Speed.io0
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v2
      - name: running Sitespeed container with options and arguments
        run: | 
           docker run --cap-add=NET_ADMIN --rm  -e REPLAY=true -e LATENCY=100 \
           sitespeedio/sitespeed.io https://procesor2017.github.io/gitHubWorkShop/ \
           -n 1 -b chrome

  #Postman RUN
  postmanRun:
    name: Postman run [NewMan CLI]
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v2
      - name: Run NEwMan
        uses: anthonyvscode/newman-action@v1
        with:
          collection: ${{ github.workspace }}/test/testapi.json
          reporters: cli
  
  #RobotFramework example how to create simple report, upload artefact etc.
  rfStartTestInDocker:
    name: Start RF test in docker and upload results to folder
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start test
      uses: joonvena/robotframework-docker-action@v0.1
      env:
        BROWSER: chrome
        ROBOT_TESTS_DIR: ${{ github.workspace }}/test/RobotFrameWork
        ROBOT_REPORTS_DIR: ${{ github.workspace }}/test/RobotFrameWork
    - name: Upload test results
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: reports
        path: ${{ github.workspace }}/test/RobotFrameWork
    
  generateReport:
    name: Generate report
    if: always()
    needs: [rfStartTestInDocker] 
    runs-on: ubuntu-latest
    steps:
    - name: Download reports
      uses: actions/download-artifact@v1
      with:
        name: reports
    - name: Get Repository Owner & Name
      run: |
        export OWNER="$(echo "${{ github.repository }}" | awk -F / '{print $1}' | sed -e "s/:refs//")"
        export REPO="$(echo "${{ github.repository }}" | awk -F / '{print $2}' | sed -e "s/:refs//")"
        echo "::set-env name=REPOSITORY_OWNER::$OWNER"
        echo "::set-env name=REPOSITORY_NAME::$REPO"
    - name: Send report to commit
      uses: joonvena/robotframework-reporter-action@v0.1
      env:
        GH_ACCESS_TOKEN: ${{ secrets.TOKEN }}
        REPO_OWNER: ${{ env.REPOSITORY_OWNER }}
        COMMIT_SHA: ${{ github.sha }}
        REPOSITORY: ${{ env.REPOSITORY_NAME }}
        REPORT_PATH: reports
   
