name: GitHub-CI
on: 
  [push]

# Jednoduchý příklad pro vypsání Ahoj :-)
jobs:
  build:
    name: Vítej
    runs-on: ubuntu-latest
    steps:
      - name: Ahoj
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Batman'
        id: ahoj
  # Startujeme RF test na API = Ukázka instalace pythonu a dalších závislostí.
  robotApiTest:
    name: robotApiTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-requests 
      - name: Start test
        run: | 
          python -m robot -i api test/RobotFrameWork/tc.robot
  # Docker and robot framework --RobotFrameWork
  robotWebTest:
    name: robotWebTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker for RF
        run: |
          docker run --shm-size=1g \
          -v ${{ github.workspace }}/test/RobotFrameWork:/opt/robotframework/reports:Z \
          -v ${{ github.workspace }}/test/RobotFrameWork:/opt/robotframework/tests:Z \
          -e BROWSER=chrome \
          --user=1001:1001 \
          ppodgorsek/robot-framework:latest
          
  #K6 Load Test
  loadTest:
    name: k6 Load Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run k6 local test
        uses: k6io/action@v0.1
        with:
          filename: ${{ github.workspace }}/test/k6/loadtest.js
          flags: --vus 50 --duration 10s
  
  # Code quality 
  codeQuality:
    name: Code Quality test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  #WebPage speed
  webPageSpeed:
    name: Code Quality test
    runs-on: ubuntu-latest
    steps:
    - name: Web Page Speed
      uses: jakepartusch/psi-action@v1
      id: psi
      with:
        url: "https://procesor2017.github.io/gitHubWorkShop/"
        threshold: 70
        strategy: mobile