name: GitHub-CI
on: 
  [push]

# Jednoduchý příklad pro vypsání Ahoj :-)
jobs:
  build:
    name: Vítej
    runs-on: ubuntu-latest
    steps:
      - name: Ahoj
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Batman'
        id: ahoj
  # Startujeme RF test na API = Ukázka instalace pythonu a další závislostí.
  robotApiTest:
    name: robotApiTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          python3 pip install robotframework
          python3 pip install robotframework-seleniumlibrary
          python3 pip install robotframework-requests 
      - name: Start test
        run: | 
          python3 -m robot -i tc01 robotframework/tc.robot
  robotWebTest:
    name: robotWebTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v0.1
        env:
          BROWSER: chrome
          ROBOT_TESTS_DIR: ${{ github.workspace }}/robotframework
          ROBOT_REPORTS_DIR: ${{ github.workspace }}/robotframework